// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZrV22ygf4kBisi3EEFYIhcdIaimnX1oQ',
    appId: '1:274139283576:web:91558a4426b1223a622d8d',
    messagingSenderId: '274139283576',
    projectId: 'will-do-a0462',
    authDomain: 'will-do-a0462.firebaseapp.com',
    storageBucket: 'will-do-a0462.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ccbthJfCN4ObEqWd_rHIuWieS205VTU',
    appId: '1:274139283576:android:a9af3d737d9559fe622d8d',
    messagingSenderId: '274139283576',
    projectId: 'will-do-a0462',
    storageBucket: 'will-do-a0462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTgCQGIwvdLTTRz3A7rkuo6D1945GFzw',
    appId: '1:274139283576:ios:4e5587b4f9a02889622d8d',
    messagingSenderId: '274139283576',
    projectId: 'will-do-a0462',
    storageBucket: 'will-do-a0462.appspot.com',
    iosClientId: '274139283576-184ftniks3lqhhaffn49935t97r1c8ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOTgCQGIwvdLTTRz3A7rkuo6D1945GFzw',
    appId: '1:274139283576:ios:4e5587b4f9a02889622d8d',
    messagingSenderId: '274139283576',
    projectId: 'will-do-a0462',
    storageBucket: 'will-do-a0462.appspot.com',
    iosClientId: '274139283576-184ftniks3lqhhaffn49935t97r1c8ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZrV22ygf4kBisi3EEFYIhcdIaimnX1oQ',
    appId: '1:274139283576:web:28efc3d103a4021a622d8d',
    messagingSenderId: '274139283576',
    projectId: 'will-do-a0462',
    authDomain: 'will-do-a0462.firebaseapp.com',
    storageBucket: 'will-do-a0462.appspot.com',
  );
}
